### PR TITLE
Check for empty or non-existent sources section in config parsing

### PR DESCRIPTION
**Pull request by no92**
Consider this minor cosmetics. This makes sure building doesn't fail if there are no declared sources.

### CODE REVIEW

**Comment by avdgrinten** [comment]
This is not only minor cosmetics but actually a very reasonable change. Thank you for the PR!

I'm not sure if we should not directly test if the object is a `list`. After all, YAML only stores lists and dicts as iterable objects and dicts would also be problematic. What do you think?

As a side note, I remember that certain other sections also need to exist (`configure` / `compile` / `build`?). As a QoL improvement those should also be made optional in the future.

**Comment by avdgrinten** [comment]
Looks good. Do you consider this PR to be complete? If yes, I will merge it.

**Comment by no92** [comment]
I'll add another commit for handling `configure`, `compile` and `build`, but after that it should be complete.

**Comment by no92** [comment]
Turned out that `configure` and `install` (in tools) were already being checked for exactly this, so that should resolve it completely. I'd consider this series complete.

It works with my bootstrap.yml, but I'm currently unable to verify against managarm's (it parses without error, but due to being on WSL right now I can't confirm by building).

**Comment by no92** [comment]
Turned out that `configure` and `install` (in tools) were already being checked for exactly this, so that should resolve it completely. I'd consider this series complete.

It works with my bootstrap.yml, but I'm currently unable to verify against managarm's (it parses without error, but due to being on WSL right now I can't confirm by building).

**Comment by avdgrinten** [comment]
The changes look good. There is no need to verify against managarm's xbstrap.yml, I will manually do this. Merging this; thanks again for the PR.

**Pull request merged**
